USE [master]
GO

/****** Object:  Database [OverSurgery]    Script Date: 1/11/2017 11:29:29 AM ******/
CREATE DATABASE [OverSurgery]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OverSurgery', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OverSurgery.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OverSurgery_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OverSurgery_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OverSurgery] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OverSurgery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OverSurgery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OverSurgery] SET ARITHABORT OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OverSurgery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OverSurgery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OverSurgery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OverSurgery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OverSurgery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OverSurgery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OverSurgery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OverSurgery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OverSurgery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OverSurgery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OverSurgery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OverSurgery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OverSurgery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OverSurgery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OverSurgery] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OverSurgery] SET  MULTI_USER 
GO

ALTER DATABASE [OverSurgery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OverSurgery] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OverSurgery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OverSurgery] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OverSurgery] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OverSurgery] SET QUERY_STORE = OFF
GO

USE [OverSurgery]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OverSurgery] SET  READ_WRITE 
GO

/****** Object:  Table [dbo].[Medicine]    Script Date: 1/11/2017 11:28:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Medicine](
	[medicineID] [int] IDENTITY(1,1) NOT NULL,
	[medicineName] [varchar](255) NULL,
	[medicineDescription] [varchar](255) NULL,
	[exxtendPrescription] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[medicineID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Patient]    Script Date: 1/11/2017 11:31:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Patient](
	[patientID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[NRIC] [varchar](100) NOT NULL,
	[dateOfBirth] [varchar](100) NOT NULL,
	[address] [varchar](500) NOT NULL,
	[phoneNo] [varchar](100) NULL,
	[email] [varchar](255) NULL,
	[gender] [varchar](100) NULL,
 CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED 
(
	[patientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Position]    Script Date: 1/11/2017 11:31:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Position](
	[positionID] [int] IDENTITY(1,1) NOT NULL,
	[positionName] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[positionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Prescription]    Script Date: 1/11/2017 11:31:50 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Prescription](
	[prescriptionID] [int] IDENTITY(1,1) NOT NULL,
	[medicineID] [int] NOT NULL,
	[staffID] [int] NOT NULL,
	[patientID] [int] NOT NULL,
	[dateTime] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[prescriptionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Report]    Script Date: 1/11/2017 11:32:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Report](
	[reportID] [int] IDENTITY(1,1) NOT NULL,
	[staffID] [nchar](225) NOT NULL,
	[patientID] [nchar](225) NOT NULL,
	[description] [nchar](500) NULL,
	[remarks] [nchar](500) NULL,
	[dateTime] [datetime] NOT NULL,
	[appointmetID] [nchar](10) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Staff]    Script Date: 1/11/2017 11:32:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Staff](
	[staffID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[workSchedule] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[staffID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[StaffPosition]    Script Date: 1/11/2017 11:32:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[StaffPosition](
	[SPID] [int] NOT NULL,
	[staffID] [int] NOT NULL,
	[patientID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
